version: '3.8'

services:
  spring-boot-app:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"